### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by yukoulah** [McSwaggens/linux-csgo-external#42]
Is there any way for have Bhop only when space key is pressed?

**Comment by McSwaggens** [comment]
_linux-csgo-external_ uses the `X` library, which is very poor and only allows us to capture input _events_ and not _key status_, on the bright side, _AimTux_ allows you to just hold down the spacebar key, this is because we're tapping into the games input, not any `X` library.

And yes... We're very close to release, we just need to iron out a few bugs.
